### ISSUE TITLE
Wrong data copied in masternode info tab

### ISSUE THREAD

**Issue by Grimer123** [dogecash/dogecash-old#31]
### Describe the issue
When open masternode tab in Wndows wallet and click 3 dots near masternode and select Info, in appeared tab pressing copy button near Public Key actually copies collateral txid (next value)
#### If so, please list the steps to reproduce below:
1. Open Masternode tab
2. Click 3 dots near your Masternode
3. Select Info
4. Press copy Public Key
5. Paste result in notepad - it is wrong

### Expected behavior
Pressing copy button should copy to clipboard corresponding value

### Actual behavior
Pressing copy button copies wrong value in clipboard

### What version of DogeCash Core are you using?
Client for Windows from official release: v5.0.1.0-86efd92f3

### Machine specs:
- OS: Windows 10
- CPU: Corei7
- RAM: 16GB
- Disk size: 500GB
- Disk Type (HD/SDD): SDD

**Comment by akshaynexus** [comment]
Fixed via https://github.com/dogecash/dogecash/commit/48e722de0f4a145b54428ad3445d0b1ac0358893
