### ISSUE TITLE
Linux 18.04 Build dependancy missing libqt5svg5-dev

### ISSUE THREAD

**Issue by waterfallm** [dogecash/dogecash-old#32]
following error message received when compiling qt on linux 18.04

"No package 'Qt5Svg' found"

this issue was correct by adding 

sudo apt install libqt5svg5-dev

then the make was produce and i was able to make qt file.

Can the linux build doc be updated to include this dependency?

**Comment by akshaynexus** [comment]
Sure, will add it to docs
