### ISSUE TITLE
missing Include file

### ISSUE THREAD

**Issue by waterfallm** [dogecash/dogecash-old#33]
qt/dogecash/moc_pwidget.cpp seems to be missing and is referenced in src/qt/dogecash/pwidget.cpp

Unable to complie qt code

**Comment by akshaynexus** [comment]
What os are you compiling on?

**Comment by waterfallm** [comment]
ubuntu 18.04 desktop

**Comment by waterfallm** [comment]
src/qt/dogecash/pwidget.cpp

5 | #include "qt/dogecash/pwidget.h"
6 | #include "qt/dogecash/qtutils.h"
7 | #include "qt/dogecash/moc_pwidget.cpp"
8 | #include "qt/dogecash/loadingdialog.h"

someting looks to be a miss with this file and it's includes

**Comment by akshaynexus** [comment]
i suggest trying  gitian compiles,on my side ive compiled via gitian and without and had no issues.try reconfiguring
