### ISSUE TITLE
wallet crash when voting

### ISSUE THREAD

**Issue by TheNerd** [dogecash/dogecash-old#40]
### Describe the issue

When clicking on yes on current proposal (April 15 2020) wallet crashes and closes. 

### Can you reliably reproduce the issue?

yes

#### If so, please list the steps to reproduce below:
1. Open wallet
2. Click governance
3. Click DOGECDevCompensation
4. Click Yes
5. Wait for wallet to disappear. 

### Expected behavior
I do not expect the wallet to crash. I would expect it to vote or to pop up a message explaining that I can't vote. 

### Actual behavior
the wallet closes

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of DogeCash Core are you using?
v5.1.1.3 binary downloaded from GitHub release page

### Machine specs:
- OS: Windows 10 1909
- CPU: I7-6700
- RAM: 16GB
- Disk size: 256GB SSD / 1tb HDD
- Disk Type (HD/SDD): SDD / HDD

### Any extra information that might be useful in the debugging process.
debug.log - https://pastebin.com/885M9NQp
db.log is empty
config.log - non-existant

**Comment by Liquid369** [comment]
Voting fixed in v5.1.17 currently in beta-testing before relase.

Thank you for the heads up and closing issue now!
