### ISSUE TITLE
No Blockupdate until 574767

### ISSUE THREAD

**Issue by zer0de** [dogecash/dogecash-old#53]
No Update since 2 weeks, runing v5.2.1.0-0a7cf1c95-dirty on Windows.

Connections 112 (In: 109 / Out: 3), the wallet runs 24/7 for staking only.

what happend threre?

it runs in the past, i think 3-4 weeks ago.

thank for information - helping

**Comment by Liquid369** [comment]
Can you get a copy of your debug.log and upload it for me so I can read whats going on.
A reindex may help as well though. 
You can try a snapshot from discord in #daily-bootstrap

**Comment by zer0de** [comment]
[debug.log on pastebin](https://pastebin.com/nnPDrzWV)

reindex is running now. if i have finished, i edit this post.

thx 4 helping

//edit

Now its finish and stay at the same point.

discord i didnt have a account

**Comment by zer0de** [comment]
the error is still current

**Comment by Liquid369** [comment]
Can you make sure you are running 5.2.2 please

**Comment by zer0de** [comment]
Now it Works.
Thanks.
