### ISSUE TITLE
No Blockupdate after 764221

### ISSUE THREAD

**Issue by zer0de** [dogecash/dogecash-old#58]
Wallet Version: 5.2.3
Windows 64bit

All steps done by updating.

Numbers of connections: 29 (In: 28 / Out: 1)

Debug Log incl. [Hostet on XUP 11Mb](http://xup.in/dl,14525376)

**Comment by ShadXo** [comment]
You need to download the bootstrap and it will sync past this.
1. Close your wallet.
2. Delete the 2 folders: blocks and chainstate.
3. download: https://www.dropbox.com/s/s4vy92sczk9c10s/blocks_n_chains.tar.gz
4. Copy the folders blocks and chainstate to the location you deleted the 2 folders from.
5. Open wallet again and let it run.

**Comment by zer0de** [comment]
Thanks a lot.
now it works
